### PR TITLE
Added Angular 11 support

### PR DESCRIPTION
**Pull request by cchulo**
I added support for Angular 11 and tested it, all animations work as intended. Note that Angular 11 project was created without strict mode enabled.

I simply created a new project and library, ported your code over. I am amazed that I did not have to touch much of the source code at all, it all worked beautifully.

I indicated in the peerDependencies to support @angular >= 9.0.0, so in theory it should work for Angular 9+? Please double check this for me.

### CODE REVIEW

**Comment by cchulo** [comment]
forgot to mention issue #24

**Comment by jiayihu** [comment]
This is quite a big change, thanks for doing it! I'll have a look at it this week-end hopefully to check everything is fine. Might also take the chance to solve #25

**Comment by jiayihu** [comment]
Thanks for the help, I've checked everything is still working and published the new 1.0 version 🎉

**Comment by cchulo** [comment]
not a problem always happy to help, nice job on this library, it was just what I was looking for 🙂

**Pull request merged**
